### ISSUE TITLE
Incompatible with phpList plugins which use local copies of jQuery

### ISSUE THREAD

**Issue by samtuke** [phpList/phplist-ui-bootlist#2]
phpList plugins which already include their own copy of jQuery are incompatible with this theme. The segmentation plugin (https://github.com/bramley/phplist-plugin-segment) for example, uses jQuery for forms on it's "Segmentation" tab in the campaign composer. This conflict must be resolved.
A possible solution could be a new policy on phpList plugin use of jQuery, with clear documentation on what jQuery version and jQuery plugins the bootlist theme supports and makes available to plugins used with it.

**Comment by tarekdj** [comment]
I think the best option is to move jQuery & jQuery UI to core. We should also agree if we need to update jQuery (if new release available) on patch release.

**Comment by mariez** [comment]
@samtuke can I close this?
