### ISSUE TITLE
Not using the updated community rss feed code

### ISSUE THREAD

**Issue by bramley** [phpList/phplist-ui-bootlist#23]
This theme doesn't have the changes made to the dressprow theme to fix the response problems  with the community rss feed.

It would seem sensible to move the bulk of that rss feed processing into core phplist with the themes dealing only with the presentation (css etc).

**Comment by michield** [comment]
Yes, I agree. We can put the rss fetching in the core

**Comment by mariez** [comment]
Is this resolved with the commit https://github.com/phpList/phplist-ui-bootlist/commit/4b19dab8c59f12d2d56db1b4bba899498d4e6468 ?

**Comment by michield** [comment]
Yes
