### ISSUE TITLE
How to style an a element as a button

### ISSUE THREAD

**Issue by bramley** [phpList/phplist-ui-bootlist#33]
In Dressprow there is a "button" CSS class that styles an `<a>` element as a button. The result looks just the same as a submit button.

There doesn't appear to be the same class in Trevellin, so is there anything else common to both themes that will do this?
Currently in Trevellin this link appears as a button but with a different background colour to real submit buttons. The styling appears to be done for btn and btn-default classes, so something is changing the button class into those classes.

`<input name="segment[save]" type="submit" value="Save segment" />        </div>
        <div class="segment-block">`

`<a target="_blank" class="button" href="./?page=configure&amp;tk=fc5c19e4302b3341470274da4fb7ecda#segmentation">Edit saved segments</a> `
![image](https://user-images.githubusercontent.com/3147688/31720792-75ca8f92-b40f-11e7-911b-12b57fcdf895.png)

**Comment by mariez** [comment]
Trevelin use Bootstrap 3 framework, you can find in this link the documentation about buttons:
https://getbootstrap.com/docs/3.3/css/#buttons

To not modify the application, Trevelin inserted bootstrap styles with this javascript:
https://github.com/phpList/phplist-ui-bootlist/blob/master/js/phpList3ToBootstrap.js

But you can add them directly in the html if you are editing a plugin.

If you want your html looks ok in both themes (Dressprow and Trevelin) I think you should keep adding the "button" class too.

Hope this help.

**Comment by bramley** [comment]
Thanks.
