### ISSUE TITLE
Webbler listing column is displayed as a button

### ISSUE THREAD

**Issue by bramley** [phpList/phplist-ui-bootlist#37]
With this theme when using a Webbler listing, a column whose value has a link is displayed as a kind of button. Some classes are added to the `<a>` element by javascript - btn btn-xs and btn-primary which appear to be responsible for the styling.
![image](https://user-images.githubusercontent.com/3147688/33728147-6cb16884-db71-11e7-87f8-4124cf3adce9.png)

Is there some way to stop this happening so that the column content is displayed similarly to the ID column in the screenshot? For comparison the Dressprow theme styles the ID and Campaign columns the same
![image](https://user-images.githubusercontent.com/3147688/33728316-fabbb9cc-db71-11e7-8c75-af6e0cc990de.png)

**Comment by bramley** [comment]
I have found that I can undo the additional styles by adding further js

`    $('.myclass span.listingelement a').removeClass('btn btn-xs btn-primary');`
and adding "myclass" to an outer element. 
![image](https://user-images.githubusercontent.com/3147688/33808895-903673c8-dde5-11e7-8059-5662c64a4ffc.png)

**Comment by mariez** [comment]
Thats great @bramley. We should add that to the theme.


mz.
-----
http://harpitoweb.com

**Comment by mariez** [comment]
@bramley I did it a bit more gerenal so you can use it on other links too. 
This is the code:
+	$('.myclass a').removeClass(function (index, css) {
+		return (css.match (/\bbt\S+/g) || []).join(' '); // removes anything that starts with "bt"
+	}); 

It is merged here https://github.com/phpList/phplist-ui-bootlist/pull/39/
Tell me if this is ok for you to close the issue.

**Comment by bramley** [comment]
Ah no, using "myclass" was just an example. That is not a good name to use.

But I can add that css to my own styles to undo the theme's style rule so I do not think that there is a need to add a similar rule into the theme. If any change is needed then is it possible to make the original rule more precise so that it matches only those a elements that want to be shown as a button?

	`$('span.listingelement a, div.configEdit a').not('body.members a.listingelement, .home span.listingelement a,a[name]').addClass('btn btn-xs btn-primary');`

**Comment by bramley** [comment]
On the Statistics page two totals are displayed as buttons whereas the campaign title is shown as an ordinary link, which is similar to my original problem 
![image](https://user-images.githubusercontent.com/3147688/34328520-8df4bef0-e8d8-11e7-8194-1cb30a428b53.png)

**Comment by mariez** [comment]
The links in Views and Clicks columns in Statistic page are buttons because the link view is too light to such a small link (only 2 or 3 characters), so the button view i think is better in that cases. 

There are a lot of links to show as a button in that tables, and not all has the "button" phplist3 style.  I dont know if i can do it more specific, but i will try.

In the meantime lets use this method. I will change the name "myclass" to "nobootstrap" to be more clear. Maybe this "nobootstrap" class can be usefull too to avoid others bootstrap styles in the future.

**Comment by bramley** [comment]
Thanks. This change works for me in that a link is no longer displayed as a button.
Also I checked several core phplist pages and those links that were previously displayed as buttons continue to do so.
