### ISSUE TITLE
Incompatible to 3.2.5 or still very WIP?

### ISSUE THREAD

**Issue by janus-reith** [phpList/phplist-ui-bootlist#4]
I build this (`npm install -g grunt-cli && npm install`) and put it to /lists/admin/ui/phplist-ui-bootstrap and pointed init.php to this theme.

It looks a bit messed up, eg. the tabs on the start page appear over the content.
There was no issue in the browser console, and the issue apperared in different browsers I tested.

Did I miss anything in the installation process?

![screen1](https://cloud.githubusercontent.com/assets/1831220/17359972/68c0fd7e-5969-11e6-87ce-7405ebeac1a6.jpg)
![screen2](https://cloud.githubusercontent.com/assets/1831220/17359973/68c1a3aa-5969-11e6-88b7-dbec65e6e732.jpg)

**Comment by tarekdj** [comment]
Hi @janus-reith, this is a work in progress. Stable release will be available soon.
Thanks!

**Comment by mariez** [comment]
The first release is available now and included in phplist 3.3.0.
